apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/base/namespaces.yaml
  - ../../base/base/ingress
  - ../../base/base/dapr-system
  - ../../base/base/storage-account
  - ../../base/base/poseidon
  - ../../base/base/sources
patchesStrategicMerge:
  - nginx.patch.yaml
