---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system-base
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: flux
  url: https://github.com/AlexisMtr/poseidon-gitops
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  include:
    # Application
    - repository:
        name: flux-system-base
      fromPath: k8s/app
      toPath: app/base
    # Infrastructure
    - repository:
        name: flux-system-base
      fromPath: k8s/infrastructure
      toPath: infrastructure/base
  ref:
    branch: main
  url: https://github.com/AlexisMtr/poseidon-gitops-tenant
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: clusters/tenant/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
